version: 2

updates:
  - package-ecosystem: uv
    directory: "/apps/mcp-atlassian"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 10
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/apps/mcp-atlassian"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 10
