apiVersion: v2
name: service-infra
description: service-infra
version: 0.1.0

dependencies:
  - repository: oci://891377205362.dkr.ecr.eu-west-1.amazonaws.com/drive/charts
    name: drive-service-infra
    alias: drive
    # Kargo manages version - this version is irrelevant
    version: 99.99.99
