name: On Push To Main

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  publish-updated-apps:
    uses: WirelessCar-WDP/drive-actions/.github/workflows/publish-generic-apps.yaml@v2.27.0
    secrets: inherit
